### PR TITLE
Add basic Travis configuration

### PR DESCRIPTION
**Pull request by sbesson**
This configuration should allow to:
- start Travis is a container based environment
- install the requirements (incl. the workaround for PIL)
- install postgresql and create a DB

### CODE REVIEW

**Comment by sbesson** [comment]
@aleksandra-tarkowska this stops at the basic requirements installation + DB creation. Do we want to create a mock settings file to be used by Travis?

**Comment by atarkowska** [comment]
@sbesson db is created in memory https://github.com/openmicroscopy/registry/pull/1/files#diff-ffbbe1add1c8c06e2fadf0390c84c781R5

just use: `python manage.py test registry --settings=omero_qa.settings-test -v 3`

**Comment by sbesson** [comment]
@aleksandra-tarkowska: last commit still failed due to cloghandler - see https://travis-ci.org/sbesson/registry/builds/82570273. Should this be added as a dependency?

**Comment by atarkowska** [comment]
@sbesson I am very sorry, yes exactly like https://github.com/openmicroscopy/stats/blob/master/requirements.txt#L42

**Comment by sbesson** [comment]
That's https://travis-ci.org/sbesson/registry/builds/82605755 green!

**Comment by atarkowska** [comment]
Great thank you so much

**Pull request merged**
